import { Geist, Geist_Mono } from 'next/font/google';
import { Orbitron } from 'next/font/google';
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

// Configuración simplificada de Orbitron
const orbitron = Orbitron({
  subsets: ["latin"],
  weight: ["400", "500", "700"], // Asegúrate de que estos pesos estén disponibles
  variable: "--font-orbitron",
  display: "swap", // Asegura que el texto sea visible mientras se carga la fuente
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} ${orbitron.variable}`}>
        {children}
      </body>
    </html>
  );
}